export const OAUTH_GITHUB_CLIENT_ID_CALLBACK =
  process.env.REACT_APP_OAUTH_GITHUB_CLIENT_ID_CALLBACK;
export const OAUTH_GITHUB_CLIENT_SECRET_CALLBACK =
  process.env.REACT_APP_OAUTH_GITHUB_CLIENT_SECRET_CALLBACK;
